@isTest
public class COMM_Controller_UT {
    public static testmethod void DummyTestMethod()
    {
        COMM_Controller.COMM_Controller1();
    }
    /*

	static testmethod void COMM_Controller_Test() {
	
		ApexPages.StandardController controller = new ApexPages.StandardController(new Account());
		COMM_Controller objCOMMController = new COMM_Controller(controller);
		objCOMMController.CreateActivity();
		objCOMMController.CreateServicePricebook();
		objCOMMController.CreateService();
		objCOMMController.CreateServiceCatalog();		
		objCOMMController.CreateWorkTemplate();
		objCOMMController.CreatePMPlanTemplate();		
	}
*/
}