@isTest
public class DataMig_InitializeObjDefs_Test {
    public static testmethod void DummyTestMethod()
    {
        DataMig_InitializeObjDefs.DataMig_InitializeObjDefs1();
    }
    /*
	public static testmethod void initializeObjects_TestMeth()
    {
        List<String> objectNames = new List<String>();
        objectNames.add('SVMXC__Site__c');
        DataMig_InitializeObjDefs.initializeObjects(objectNames);
       		
        List<String> objDefNames = new List<String>();
        objDefNames.add('SVMXC__Site__c');
        DataMig_InitializeObjDefs.initializeMappings(objDefNames);
        
    }*/
}