@isTest(seeAllData=true)
Private class Milestone1_milestone_trigger_test{
    static testMethod void myUnittest(){
        /*
        Opportunity opp=[select id from Opportunity limit 1];
        Milestone1_Milestone__c testMile = new  Milestone1_Milestone__c();
        Milestone1_Milestone__c ml = [select id, name from Milestone1_Milestone__c limit 1];
        testMile.Name='Mile123';
        testMile.Type__c='Installation';
        testMile.Opportunity__c=opp.id;
        insert testMile;
        testMile.Name='Mile1234';
        update testMile;
        delete testMile;
*/
    }
}